### ISSUE TITLE
Fix for node 14

### ISSUE THREAD

**Issue by flying-sheep** [unional/ava-fixture#82]
Note 14 interprets this as ES2015 module and therefore one has to do:

```js
import fixture from 'ava-fixture'

fixture.default(ava, ...)
```

To fix this, you should do this: https://nodejs.org/api/esm.html#esm_dual_commonjs_es_module_packages

**Comment by unional** [comment]
Thanks. Will take a look into it.
But at the same time, you can check out `@unional/fixture`, I have moved most of the functionality there and that is not coupled to `ava`. :)

**Comment by flying-sheep** [comment]
Thank you for the pointer!
